### ISSUE TITLE
Volume status is not updating properly at etcd server when start and stop actions performed

### ISSUE THREAD

**Issue by kamleshverma1** [Tendrl/gluster-integration#69] opened 2016-11-24 06:26 UTC
Volume status is not updating properly at etcd server when start and stop actions performed.

**Comment by anmolsachan** [comment] 2017-01-18 07:01
The issue is resolved now. Verification required with the stable release before closing.

**Comment by sankarshanmukhopadhyay** [comment] 2017-02-24 00:55
It has being a while and a few builds tested since. Please confirm that this is indeed working and close this particular issue. @anmolsachan

**Comment by anmolsachan** [comment] 2017-02-27 11:41
Volume status is now being updated properly, according to the latest master code. The issue can be closed now.

**Closed** 2017-03-16 23:04 UTC
